import { Roboto_Serif } from 'next/font/google'
import './globals.css'

const robotoSerif = Roboto_Serif({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotoSerif.className}>{children}</body>
    </html>
  )
}
